In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import csv
#import requests
#import time

In [2]:
#List of 16 main topics found on emeritus.org/explore-topics/
aidata_to_load = "keywordsbycategory/aikeywords.csv"

In [4]:
#look at sample of data
aidata = pd.read_csv(aidata_to_load)
aidata.head()

,Keyword,Currency,Avg. monthly searches,Competition,Competition (indexed value),Top of page bid (low range),Top of page bid (high range),Ad impression share,Organic impression share,Organic average position,...,Searches: Oct 2020,Searches: Nov 2020,Searches: Dec 2020,Searches: Jan 2021,Searches: Feb 2021,Searches: Mar 2021,Searches: Apr 2021,Searches: May 2021,Searches: Jun 2021,Searches: Jul 2021
0,machine learning certification,USD,5000.0,High,83.0,6.83,18.00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,artificial intelligence course,USD,500.0,High,82.0,5.98,15.67,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,machine learning course,USD,5000.0,High,82.0,5.18,16.00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,artificial intelligence and machine learning,USD,5000.0,Medium,65.0,6.18,40.11,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,machine learning online course,USD,500.0,High,75.0,6.45,15.32,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#In the table above, the column "Keyword" is the only one of interest, since we will be using the API to collect keyword volume data
#Since the keywords from the 16 topics will be merged, the following code will add a column with the topic name the keyword was generated from
aidata['Topic'] = "Artificial Intelligence and Machine Learning"
aidata.to_csv(aidata_to_load, index=False)
aidata.head()

,Keyword,Currency,Avg. monthly searches,Competition,Competition (indexed value),Top of page bid (low range),Top of page bid (high range),Ad impression share,Organic impression share,Organic average position,...,Searches: Nov 2020,Searches: Dec 2020,Searches: Jan 2021,Searches: Feb 2021,Searches: Mar 2021,Searches: Apr 2021,Searches: May 2021,Searches: Jun 2021,Searches: Jul 2021,Topic
0,machine learning certification,USD,5000.0,High,83.0,6.83,18.00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Artificial Intelligence and Machine Learning
1,artificial intelligence course,USD,500.0,High,82.0,5.98,15.67,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Artificial Intelligence and Machine Learning
2,machine learning course,USD,5000.0,High,82.0,5.18,16.00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Artificial Intelligence and Machine Learning
3,artificial intelligence and machine learning,USD,5000.0,Medium,65.0,6.18,40.11,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Artificial Intelligence and Machine Learning
4,machine learning online course,USD,500.0,High,75.0,6.45,15.32,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Artificial Intelligence and Machine Learning

In [7]:
codingdata_to_load = "keywordsbycategory/codingkeywords.csv"
datadata_to_load = "keywordsbycategory/datakeywords.csv"
digitalmarketingdata_to_load = "keywordsbycategory/digitalmarketingkeywords.csv"
digitaltransformationdata_to_load = "keywordsbycategory/digitaltransformationkeywords.csv"
entrepeneurshipdata_to_load = "keywordsbycategory/entrepeneurshipkeywords.csv"
financedata_to_load = "keywordsbycategory/financekeywords.csv"
healthcaredata_to_load = "keywordsbycategory/healthcarekeywords.csv"
hrdata_to_load = "keywordsbycategory/hrkeywords.csv"
leadershipdata_to_load = "keywordsbycategory/leadershipkeywords.csv"
managementdata_to_load = "keywordsbycategory/managementkeywords.csv"
productdata_to_load = "keywordsbycategory/productkeywords.csv"
projectdata_to_load = "keywordsbycategory/projectkeywords.csv"
salesdata_to_load = "keywordsbycategory/saleskeywords.csv"
strategydata_to_load = "keywordsbycategory/strategykeywords.csv"
techdata_to_load = "keywordsbycategory/techkeywords.csv"

In [9]:
#read the rest of the CSVs
codingdata = pd.read_csv(codingdata_to_load)
datadata = pd.read_csv(datadata_to_load)
digitalmarketingdata = pd.read_csv(digitalmarketingdata_to_load)
digitaltransformationdata = pd.read_csv(digitaltransformationdata_to_load)
entrepeneurshipdata = pd.read_csv(entrepeneurshipdata_to_load)
financedata = pd.read_csv(financedata_to_load)
healthcaredata = pd.read_csv(healthcaredata_to_load)
hrdata = pd.read_csv(hrdata_to_load)
leadershipdata = pd.read_csv(leadershipdata_to_load)
managementdata = pd.read_csv(managementdata_to_load)
productdata = pd.read_csv(productdata_to_load)
projectdata = pd.read_csv(projectdata_to_load)
salesdata = pd.read_csv(salesdata_to_load)
strategydata = pd.read_csv(strategydata_to_load)
techdata = pd.read_csv(techdata_to_load)

In [10]:
codingdata['Topic'] = "Coding"
codingdata.to_csv(codingdata_to_load, index=False)

datadata['Topic'] = "Data Science and Analytics"
datadata.to_csv(datadata_to_load, index=False)

digitalmarketingdata['Topic'] = "Digital Marketing"
digitalmarketingdata.to_csv(digitalmarketingdata_to_load, index=False)

digitaltransformationdata['Topic'] = "Digital Transformation"
digitaltransformationdata.to_csv(digitaltransformationdata_to_load, index=False)

entrepeneurshipdata['Topic'] = "Entrepeneurship"
entrepeneurshipdata.to_csv(entrepeneurshipdata_to_load, index=False)

financedata['Topic'] = "Finance"
financedata.to_csv(financedata_to_load, index=False)

healthcaredata['Topic'] = "Healthcare"
healthcaredata.to_csv(healthcaredata_to_load, index=False)

hrdata['Topic'] = "Human Resources"
hrdata.to_csv(hrdata_to_load, index=False)

leadershipdata['Topic'] = "Leadership"
leadershipdata.to_csv(leadershipdata_to_load, index=False)

managementdata['Topic'] = "Business Management"
managementdata.to_csv(managementdata_to_load, index=False)

productdata['Topic'] = "Product Design and Innovation"
productdata.to_csv(productdata_to_load, index=False)

projectdata['Topic'] = "Project Management"
projectdata.to_csv(projectdata_to_load, index=False)

salesdata['Topic'] = "Sales and Marketing"
salesdata.to_csv(salesdata_to_load, index=False)

strategydata['Topic'] = "Strategy and Innovation"
strategydata.to_csv(strategydata_to_load, index=False)

techdata['Topic'] = "Technology"
techdata.to_csv(techdata_to_load, index=False)

In [31]:
import glob

path = r'/Users/regana/Documents/Job Search/Coding Assignments/Emeritus/keywordsbycategory'
all_files = glob.glob(path + "/*.csv")

csvlist = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    csvlist.append(df)

df1 = pd.concat(csvlist, axis=0, ignore_index=True)
df1.head()

,Keyword,Currency,Avg. monthly searches,Competition,Competition (indexed value),Top of page bid (low range),Top of page bid (high range),Ad impression share,Organic impression share,Organic average position,...,Searches: Nov 2020,Searches: Dec 2020,Searches: Jan 2021,Searches: Feb 2021,Searches: Mar 2021,Searches: Apr 2021,Searches: May 2021,Searches: Jun 2021,Searches: Jul 2021,Topic
0,online schools,USD,50000.0,High,91.0,14.38,71.31,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Product Design and Innovation
1,online certificate programs,USD,50000.0,High,95.0,6.33,19.86,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Product Design and Innovation
2,online universities,USD,5000.0,High,94.0,21.88,69.83,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Product Design and Innovation
3,diploma certificate,USD,5000.0,High,100.0,1.19,7.90,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Product Design and Innovation
4,online courses with certificate,USD,5000.0,High,94.0,6.33,25.27,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Product Design and Innovation

In [33]:
keyworddf = df1[['Keyword','Topic']]
keyworddf.head()

                           Keyword                          Topic
0                   online schools  Product Design and Innovation
1      online certificate programs  Product Design and Innovation
2              online universities  Product Design and Innovation
3              diploma certificate  Product Design and Innovation
4  online courses with certificate  Product Design and Innovation

In [34]:
#Saves a .csv of the full list of keywords and topics as "keywordsfull.csv"
keyworddf.to_csv(r'/Users/regana/Documents/Job Search/Coding Assignments/Emeritus/keywordsfull.csv', index = False)